name: build
on:
  push:
    branches:
      - develop
jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install hathora -g
      - run: hathora cloud deploy --appName hathora-platformer --token ${{ secrets.HATHORA_TOKEN }}
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install hathora surge -g
      - run: COORDINATOR_HOST=coordinator.hathora.com APP_SECRET=${{ secrets.APP_SECRET }} hathora build --only client
      - run: cp client/web/dist/index.html client/web/dist/200.html
      - run: surge client/web/dist phaser-hathora.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
