name: build
on: [push]
jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install hathora -g
      - run: hathora cloud deploy --appName hathora-platformer --token ${{ secrets.HATHORA_TOKEN }}
