name: build
on:
  push:
    branches:
      - develop
jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g @hathora/cli
      - run: hathora-cloud deploy --appId app-f335fd9b-e94e-48b8-b7bf-858b8e06f198 --token ${{ secrets.HATHORA_CLOUD_TOKEN }}
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install hathora surge -g
      - run: HATHORA_APP_ID=app-f335fd9b-e94e-48b8-b7bf-858b8e06f198 hathora build --only client
      - run: cp client/web/dist/index.html client/web/dist/200.html
      - run: surge client/web/dist phaser-hathora.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
